=== gcarpen480/1DAM/LENGUAJES DE MARCAS/PRUEBA/PRUEBA EXAMEN_2/dtd/solucion.dtd
<!-- Esto es la gramatica del examen de tema 1 -->
<!ELEMENT tienda (inventario,configuraciones)>

<!ATTLIST tienda nombre CDATA     #REQUIRED>
<!ELEMENT inventario (componente+)>

<!ELEMENT componente (cantidad,fabricante,(caract_ram|caract_micro|caract_chasis))>
<!ATTLIST componente denominacion   CDATA       #REQUIRED
                     tipo           CDATA       #REQUIRED
                     proveedor      CDATA      #REQUIRED>

<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT fabricante (#PCDATA)>
<!ELEMENT caract_ram EMPTY>
<!ATTLIST caract_ram tam            CDATA     #REQUIRED
                     frecuencia     CDATA     #REQUIRED
                     tecnologia     CDATA     #REQUIRED>

<!ELEMENT caract_chasis EMPTY>
<!ATTLIST caract_chasis ancho           CDATA  #REQUIRED
                        largo           CDATA  #REQUIRED
                        alto            CDATA  #REQUIRED
                        compatibilidad  CDATA  #REQUIRED>
<!ELEMENT caract_micro EMPTY>
<!ATTLIST caract_micro socket       CDATA     #REQUIRED
                       frecuencia   CDATA     #REQUIRED
                       cores        CDATA     #REQUIRED
                       maxmem       CDATA     #REQUIRED>

<!ELEMENT configuraciones (equipo+)>
<!ELEMENT equipo (precio,componentes)>
<!ATTLIST equipo nombre CDATA #REQUIRED>

<!ELEMENT precio (#PCDATA)>

<!ELEMENT componentes (#PCDATA)>
<!ATTLIST componentes ref CDATA #REQUIRED>

=== gcarpen480/1DAM/LENGUAJES DE MARCAS/PRUEBA/PRUEBA EXAMEN_2/SolucionPropuesta.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tienda SYSTEM "dtd/solucion.dtd">
<tienda nombre="TodoPC">
   <inventario>
      <componente denominacion="RAM_32GB_KIngston" tipo="RAM" proveedor="Maquinones baratitos">
         <cantidad>5</cantidad>
         <fabricante>Kingston</fabricante>
         <caract_ram tam="32" frecuencia="2133" tecnologia="DDR5"/>
      </componente>
      <componente denominacion="Crux_Nox" tipo="chasis" proveedor="Maquinones baratitos">
         <cantidad>4</cantidad>
         <fabricante>Nox</fabricante>
         <caract_chasis ancho="110" largo="50" alto="80" compatibilidad="micro-ATX mini-ITX ATX" />
      </componente>
      <componente denominacion="AMD_Ryzen9_7950X" tipo="micro" proveedor="X">
         <cantidad>10</cantidad>
         <fabricante>AMD</fabricante>
         <caract_micro socket="AM5 LGA1718" frecuencia="4.5" cores="16" maxmem="128"/>
      </componente>

      <!-- Otros componentes del inventario -->
   </inventario>

   <configuraciones>
      <equipo nombre="PC de ensueÃ±o">
         <precio>515</precio>
         <componentes ref="AMD_Ryzen9_7950X Crux_Nox RAM_32GB_Kingston"/>
      </equipo>

      <!--  Otros equipos -->
   </configuraciones>
</tienda>
